In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importing the train Data set
df = pd.read_csv("training_data.csv")
df

Date Tenor       0.1       0.2       0.3       0.4       0.5  \
0      01-05-2017    2M  0.468214  0.419251  0.376260  0.338158  0.304372   
1      01-05-2017    3M  0.458471  0.412710  0.372717  0.337489  0.306511   
2      01-05-2017    6M  0.410305  0.374189  0.343045  0.316070  0.292842   
3      01-05-2017    9M  0.385267  0.354580  0.328360  0.305878  0.286712   
4      01-05-2017    1Y  0.358986  0.333608  0.312126  0.293870  0.278408   
...           ...   ...       ...       ...       ...       ...       ...   
13637  10/14/2019   15Y  0.290467  0.274071  0.259819  0.247286  0.236167   
13638  10/14/2019   20Y  0.279726  0.263635  0.249695  0.237473  0.226660   
13639  10/14/2019   25Y  0.275693  0.259711  0.245916  0.233859  0.223221   
13640  10/14/2019   30Y  0.271637  0.256054  0.242648  0.230965  0.220685   
13641  10/14/2019   40Y  0.266593  0.251865  0.239246  0.228285  0.218661   

            0.6       0.7       0.8  ...         1       1.1       1.2  \
0      0.274823  0.250066  0.231535  ...  0.220933  0.228418  0.240437   
1      0.279714  0.257540  0.241007  ...  0.229423  0.233839  0.242411   
2      0.273231  0.257346  0.245440  ...  0.234116  0.234078  0.236765   
3      0.270643  0.257590  0.247529  ...  0.236030  0.234085  0.234121   
4      0.265457  0.254819  0.246339  ...  0.235185  0.232109  0.230384   
...         ...       ...       ...  ...       ...       ...       ...   
13637  0.226238  0.217329  0.209309  ...  0.195550  0.189663  0.184359   
13638  0.217030  0.208411  0.200674  ...  0.187456  0.181826  0.176772   
13639  0.213769  0.205330  0.197769  ...  0.184884  0.179409  0.174499   
13640  0.211571  0.203450  0.196186  ...  0.183826  0.178577  0.173867   
13641  0.210144  0.202557  0.195766  ...  0.184171  0.179214  0.174736   

            1.3       1.4       1.5       1.6       1.7       1.8       1.9  
0      0.254316  0.268613  0.282659  0.296172  0.309045  0.321260  0.332831  
1      0.253100  0.264611  0.276244  0.287647  0.298654  0.309196  0.319254  
2      0.241295  0.246945  0.253200  0.259726  0.266312  0.272831  0.279207  
3      0.235658  0.238264  0.241586  0.245360  0.249397  0.253564  0.257773  
4      0.229760  0.230003  0.230908  0.232303  0.234052  0.236049  0.238213  
...         ...       ...       ...       ...       ...       ...       ...  
13637  0.179593  0.175321  0.171508  0.168118  0.165119  0.162481  0.160172  
13638  0.172247  0.168208  0.164617  0.161440  0.158642  0.156194  0.154063  
13639  0.170106  0.166187  0.162703  0.159618  0.156900  0.154517  0.152440  
13640  0.169647  0.165873  0.162507  0.159514  0.156861  0.154518  0.152458  
13641  0.170689  0.167031  0.163726  0.160742  0.158050  0.155624  0.153441  

[13642 rows x 21 columns]

In [3]:
#performing the EDA (Exploratory Data Analysis)

In [4]:
#checking non or null values
df.isnull().sum()

Date     0
Tenor    0
0.1      0
0.2      0
0.3      0
0.4      0
0.5      0
0.6      0
0.7      0
0.8      0
0.9      0
1        0
1.1      0
1.2      0
1.3      0
1.4      0
1.5      0
1.6      0
1.7      0
1.8      0
1.9      0
dtype: int64

In [5]:
#checking object type and more
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13642 entries, 0 to 13641
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    13642 non-null  object 
 1   Tenor   13642 non-null  object 
 2   0.1     13642 non-null  float64
 3   0.2     13642 non-null  float64
 4   0.3     13642 non-null  float64
 5   0.4     13642 non-null  float64
 6   0.5     13642 non-null  float64
 7   0.6     13642 non-null  float64
 8   0.7     13642 non-null  float64
 9   0.8     13642 non-null  float64
 10  0.9     13642 non-null  float64
 11  1       13642 non-null  float64
 12  1.1     13642 non-null  float64
 13  1.2     13642 non-null  float64
 14  1.3     13642 non-null  float64
 15  1.4     13642 non-null  float64
 16  1.5     13642 non-null  float64
 17  1.6     13642 non-null  float64
 18  1.7     13642 non-null  float64
 19  1.8     13642 non-null  float64
 20  1.9     13642 non-null  float64
dtypes: float64(19), object(2)
memory us

In [6]:
df.describe()

0.1           0.2           0.3           0.4           0.5  \
count  13642.000000  13642.000000  13642.000000  13642.000000  13642.000000   
mean       0.331881      0.302007      0.276614      0.254600      0.235275   
std        0.083411      0.072003      0.062428      0.054320      0.047522   
min        0.205536      0.189889      0.172411      0.156772      0.143881   
25%        0.284578      0.260605      0.239663      0.221827      0.206527   
50%        0.316036      0.288831      0.265497      0.245631      0.228131   
75%        0.351950      0.323987      0.300552      0.280610      0.262412   
max        0.687277      0.630411      0.578715      0.531344      0.487723   

                0.6           0.7           0.8           0.9             1  \
count  13642.000000  13642.000000  13642.000000  13642.000000  13642.000000   
mean       0.218217      0.203196      0.190163      0.179293      0.171110   
std        0.042011      0.037857      0.035125      0.033674      0.032751   
min        0.133259      0.124634      0.117846      0.112773      0.109262   
25%        0.193467      0.181453      0.169807      0.157350      0.148284   
50%        0.211791      0.197402      0.183689      0.172807      0.165296   
75%        0.245555      0.229335      0.215078      0.203704      0.194748   
max        0.447510      0.410605      0.377628      0.349102      0.325423   

                1.1           1.2           1.3           1.4           1.5  \
count  13642.000000  13642.000000  13642.000000  13642.000000  13642.000000   
mean       0.166120      0.163719      0.162966      0.163281      0.164325   
std        0.031422      0.030401      0.030575      0.031971      0.034235   
min        0.107101      0.106039      0.105816      0.105809      0.105756   
25%        0.144388      0.144330      0.143022      0.140938      0.139484   
50%        0.160233      0.157826      0.158158      0.158908      0.160004   
75%        0.188452      0.185057      0.183825      0.185184      0.186287   
max        0.307731      0.296794      0.292353      0.293139      0.297555   

                1.6           1.7           1.8           1.9  
count  13642.000000  13642.000000  13642.000000  13642.000000  
mean       0.165879      0.167792      0.169955      0.172287  
std        0.036997      0.039990      0.043047      0.046072  
min        0.106092      0.106715      0.107545      0.108523  
25%        0.138606      0.138217      0.138277      0.138685  
50%        0.160282      0.160519      0.161216      0.162009  
75%        0.186490      0.187732      0.189240      0.191447  
max        0.305900      0.316892      0.328164      0.340378

In [7]:
# Here we are making a copy of dataset for manipulation of data
df1 = df.copy()

In [8]:
# Total Days in Dataset
count = len(df1['Date'])//19
count

718

In [9]:
#Making a column count
lst = [i for i in range(1,count+1) for _ in range(19)]
len(lst)

13642

In [10]:
# Adding the list to our dataset
df1.insert(2,'Count',lst)
df1.head()

Date Tenor  Count       0.1       0.2       0.3       0.4       0.5  \
0  01-05-2017    2M      1  0.468214  0.419251  0.376260  0.338158  0.304372   
1  01-05-2017    3M      1  0.458471  0.412710  0.372717  0.337489  0.306511   
2  01-05-2017    6M      1  0.410305  0.374189  0.343045  0.316070  0.292842   
3  01-05-2017    9M      1  0.385267  0.354580  0.328360  0.305878  0.286712   
4  01-05-2017    1Y      1  0.358986  0.333608  0.312126  0.293870  0.278408   

        0.6       0.7  ...         1       1.1       1.2       1.3       1.4  \
0  0.274823  0.250066  ...  0.220933  0.228418  0.240437  0.254316  0.268613   
1  0.279714  0.257540  ...  0.229423  0.233839  0.242411  0.253100  0.264611   
2  0.273231  0.257346  ...  0.234116  0.234078  0.236765  0.241295  0.246945   
3  0.270643  0.257590  ...  0.236030  0.234085  0.234121  0.235658  0.238264   
4  0.265457  0.254819  ...  0.235185  0.232109  0.230384  0.229760  0.230003   

        1.5       1.6       1.7       1.8       1.9  
0  0.282659  0.296172  0.309045  0.321260  0.332831  
1  0.276244  0.287647  0.298654  0.309196  0.319254  
2  0.253200  0.259726  0.266312  0.272831  0.279207  
3  0.241586  0.245360  0.249397  0.253564  0.257773  
4  0.230908  0.232303  0.234052  0.236049  0.238213  

[5 rows x 22 columns]

In [11]:
# Here we converting Tenor (Categorical) data type to Integer data type 
names = list("Tenor_"+df1['Tenor'][:19])
names

['Tenor_2M',
 'Tenor_3M',
 'Tenor_6M',
 'Tenor_9M',
 'Tenor_1Y',
 'Tenor_2Y',
 'Tenor_3Y',
 'Tenor_4Y',
 'Tenor_5Y',
 'Tenor_6Y',
 'Tenor_7Y',
 'Tenor_8Y',
 'Tenor_9Y',
 'Tenor_10Y',
 'Tenor_15Y',
 'Tenor_20Y',
 'Tenor_25Y',
 'Tenor_30Y',
 'Tenor_40Y']

In [12]:
for i in names:
    df1[i]=0
df1.tail()

Date Tenor  Count       0.1       0.2       0.3       0.4  \
13637  10/14/2019   15Y    718  0.290467  0.274071  0.259819  0.247286   
13638  10/14/2019   20Y    718  0.279726  0.263635  0.249695  0.237473   
13639  10/14/2019   25Y    718  0.275693  0.259711  0.245916  0.233859   
13640  10/14/2019   30Y    718  0.271637  0.256054  0.242648  0.230965   
13641  10/14/2019   40Y    718  0.266593  0.251865  0.239246  0.228285   

            0.5       0.6       0.7  ...  Tenor_6Y  Tenor_7Y  Tenor_8Y  \
13637  0.236167  0.226238  0.217329  ...         0         0         0   
13638  0.226660  0.217030  0.208411  ...         0         0         0   
13639  0.223221  0.213769  0.205330  ...         0         0         0   
13640  0.220685  0.211571  0.203450  ...         0         0         0   
13641  0.218661  0.210144  0.202557  ...         0         0         0   

       Tenor_9Y  Tenor_10Y  Tenor_15Y  Tenor_20Y  Tenor_25Y  Tenor_30Y  \
13637         0          0          0          0          0          0   
13638         0          0          0          0          0          0   
13639         0          0          0          0          0          0   
13640         0          0          0          0          0          0   
13641         0          0          0          0          0          0   

       Tenor_40Y  
13637          0  
13638          0  
13639          0  
13640          0  
13641          0  

[5 rows x 41 columns]

In [13]:
df1.columns

Index(['Date', 'Tenor', 'Count', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6',
       '0.7', '0.8', '0.9', '1', '1.1', '1.2', '1.3', '1.4', '1.5', '1.6',
       '1.7', '1.8', '1.9', 'Tenor_2M', 'Tenor_3M', 'Tenor_6M', 'Tenor_9M',
       'Tenor_1Y', 'Tenor_2Y', 'Tenor_3Y', 'Tenor_4Y', 'Tenor_5Y', 'Tenor_6Y',
       'Tenor_7Y', 'Tenor_8Y', 'Tenor_9Y', 'Tenor_10Y', 'Tenor_15Y',
       'Tenor_20Y', 'Tenor_25Y', 'Tenor_30Y', 'Tenor_40Y'],
      dtype='object')

In [14]:
for i in range(len(df1['Tenor'])):
    if df1['Tenor'][i]=='2M':
        df1['Tenor_2M'][i]=1
    elif df1['Tenor'][i]=='3M':
        df1['Tenor_3M'][i]=1
    elif df1['Tenor'][i]=='6M':
        df1['Tenor_6M'][i]=1
    elif df1['Tenor'][i]=='9M':
        df1['Tenor_9M'][i]=1
    elif df1['Tenor'][i]=='1Y':
        df1['Tenor_1Y'][i]=1
    elif df1['Tenor'][i]=='2Y':
        df1['Tenor_2Y'][i]=1
    elif df1['Tenor'][i]=='3Y':
        df1['Tenor_3Y'][i]=1
    elif df1['Tenor'][i]=='4Y':
        df1['Tenor_4Y'][i]=1
    elif df1['Tenor'][i]=='5Y':
        df1['Tenor_5Y'][i]=1
    elif df1['Tenor'][i]=='6Y':
        df1['Tenor_6Y'][i]=1
    elif df1['Tenor'][i]=='7Y':
        df1['Tenor_7Y'][i]=1
    elif df1['Tenor'][i]=='8Y':
        df1['Tenor_8Y'][i]=1
    elif df1['Tenor'][i]=='9Y':
        df1['Tenor_9Y'][i]=1
    elif df1['Tenor'][i]=='10Y':
        df1['Tenor_10Y'][i]=1
    elif df1['Tenor'][i]=='15Y':
        df1['Tenor_15Y'][i]=1
    elif df1['Tenor'][i]=='20Y':
        df1['Tenor_20Y'][i]=1
    elif df1['Tenor'][i]=='25Y':
        df1['Tenor_30Y'][i]=1
    elif df1['Tenor'][i]=='30Y':
        df1['Tenor_30Y'][i]=1
    elif df1['Tenor'][i]=='40Y':
        df1['Tenor_40Y'][i]=1
    else:
        df1['Tenor'][i]=0

<ipython-input-14-689f46afee23>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Tenor_2M'][i]=1
<ipython-input-14-689f46afee23>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Tenor_3M'][i]=1
<ipython-input-14-689f46afee23>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Tenor_6M'][i]=1
<ipython-input-14-689f46afee23>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See th

In [15]:
# Here we converted our Tenor Categorical varible into integer varible
df1.tail(19)

Date Tenor  Count       0.1       0.2       0.3       0.4  \
13623  10/14/2019    2M    718  0.646292  0.585409  0.530770  0.481177   
13624  10/14/2019    3M    718  0.583260  0.530586  0.483445  0.440806   
13625  10/14/2019    6M    718  0.494512  0.453902  0.417760  0.385281   
13626  10/14/2019    9M    718  0.461384  0.425116  0.392924  0.364078   
13627  10/14/2019    1Y    718  0.432077  0.400087  0.371766  0.346455   
13628  10/14/2019    2Y    718  0.372875  0.349009  0.328064  0.309517   
13629  10/14/2019    3Y    718  0.353346  0.332079  0.313461  0.297008   
13630  10/14/2019    4Y    718  0.340404  0.320518  0.303135  0.287793   
13631  10/14/2019    5Y    718  0.330234  0.311411  0.294974  0.280476   
13632  10/14/2019    6Y    718  0.324361  0.305932  0.289844  0.275654   
13633  10/14/2019    7Y    718  0.319508  0.301460  0.285711  0.271822   
13634  10/14/2019    8Y    718  0.314505  0.296786  0.281329  0.267700   
13635  10/14/2019    9Y    718  0.310366  0.292960  0.277782  0.264402   
13636  10/14/2019   10Y    718  0.306925  0.289818  0.274907  0.261766   
13637  10/14/2019   15Y    718  0.290467  0.274071  0.259819  0.247286   
13638  10/14/2019   20Y    718  0.279726  0.263635  0.249695  0.237473   
13639  10/14/2019   25Y    718  0.275693  0.259711  0.245916  0.233859   
13640  10/14/2019   30Y    718  0.271637  0.256054  0.242648  0.230965   
13641  10/14/2019   40Y    718  0.266593  0.251865  0.239246  0.228285   

            0.5       0.6       0.7  ...  Tenor_6Y  Tenor_7Y  Tenor_8Y  \
13623  0.435823  0.394224  0.356236  ...         0         0         0   
13624  0.401981  0.366564  0.334427  ...         0         0         0   
13625  0.355927  0.329362  0.305427  ...         0         0         0   
13626  0.338084  0.314622  0.293518  ...         0         0         0   
13627  0.323698  0.303190  0.284738  ...         0         0         0   
13628  0.292998  0.278242  0.265059  ...         0         0         0   
13629  0.282372  0.269301  0.257608  ...         0         0         0   
13630  0.274158  0.261987  0.251097  ...         0         0         0   
13631  0.267595  0.256094  0.245795  ...         0         0         0   
13632  0.263045  0.251780  0.241683  ...         1         0         0   
13633  0.259479  0.248448  0.238553  ...         0         1         0   
13634  0.255586  0.244756  0.235035  ...         0         0         1   
13635  0.252510  0.241875  0.232326  ...         0         0         0   
13636  0.250087  0.239643  0.230261  ...         0         0         0   
13637  0.236167  0.226238  0.217329  ...         0         0         0   
13638  0.226660  0.217030  0.208411  ...         0         0         0   
13639  0.223221  0.213769  0.205330  ...         0         0         0   
13640  0.220685  0.211571  0.203450  ...         0         0         0   
13641  0.218661  0.210144  0.202557  ...         0         0         0   

       Tenor_9Y  Tenor_10Y  Tenor_15Y  Tenor_20Y  Tenor_25Y  Tenor_30Y  \
13623         0          0          0          0          0          0   
13624         0          0          0          0          0          0   
13625         0          0          0          0          0          0   
13626         0          0          0          0          0          0   
13627         0          0          0          0          0          0   
13628         0          0          0          0          0          0   
13629         0          0          0          0          0          0   
13630         0          0          0          0          0          0   
13631         0          0          0          0          0          0   
13632         0          0          0          0          0          0   
13633         0          0          0          0          0          0   
13634         0          0          0          0          0          0   
13635         1          0          0          0          0          0   
13636         0

In [16]:
# Making Features for prdiction the values using count and Tenor
#X_features = np.array(df1['Count']).reshape(-1,1)
X_features = np.array([df1['Count'],df1['Tenor_2M'],df1['Tenor_3M'],df1['Tenor_6M'],df1['Tenor_9M'],df1['Tenor_1Y'],df1['Tenor_2Y'],df1['Tenor_3Y'],df1['Tenor_4Y'],df1['Tenor_5Y'],df1['Tenor_6Y'],df1['Tenor_7Y'],df1['Tenor_8Y'],df1['Tenor_9Y'],df1['Tenor_10Y'],df1['Tenor_15Y'],df1['Tenor_20Y'],df1['Tenor_25Y'],df1['Tenor_30Y'],df1['Tenor_40Y']]).transpose()
print(X_features)
print(X_features.shape)

[[  1   1   0 ...   0   0   0]
 [  1   0   1 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 ...
 [718   0   0 ...   0   1   0]
 [718   0   0 ...   0   1   0]
 [718   0   0 ...   0   0   1]]
(13642, 20)


In [17]:
Count_array = np.array([i for i in range(719,count+61) for _ in range(19)])
#print(len(X_test))
X_test = np.array([Count_array,df1['Tenor_2M'][:1140],df1['Tenor_3M'][:1140],df1['Tenor_6M'][:1140],df1['Tenor_9M'][:1140],df1['Tenor_1Y'][:1140],df1['Tenor_2Y'][:1140],df1['Tenor_3Y'][:1140],df1['Tenor_4Y'][:1140],df1['Tenor_5Y'][:1140],df1['Tenor_6Y'][:1140],df1['Tenor_7Y'][:1140],df1['Tenor_8Y'][:1140],df1['Tenor_9Y'][:1140],df1['Tenor_10Y'][:1140],df1['Tenor_15Y'][:1140],df1['Tenor_20Y'][:1140],df1['Tenor_25Y'][:1140],df1['Tenor_30Y'][:1140],df1['Tenor_40Y'][:1140]]).transpose()
print(X_test)

[[719   1   0 ...   0   0   0]
 [719   0   1 ...   0   0   0]
 [719   0   0 ...   0   0   0]
 ...
 [778   0   0 ...   0   1   0]
 [778   0   0 ...   0   1   0]
 [778   0   0 ...   0   0   1]]


In [18]:
Y1 = np.array(df1['0.1'])
Y2 = np.array(df1['0.2'])
Y3 = np.array(df1['0.3'])
Y4 = np.array(df1['0.4'])
Y5 = np.array(df1['0.5'])
Y6 = np.array(df1['0.6'])
Y7 = np.array(df1['0.7'])
Y8 = np.array(df1['0.8'])
Y9 = np.array(df1['0.9'])
Y10 = np.array(df1['1'])
Y11 = np.array(df1['1.1'])
Y12 = np.array(df1['1.2'])
Y13 = np.array(df1['1.3'])
Y14 = np.array(df1['1.4'])
Y15 = np.array(df1['1.5'])
Y16 = np.array(df1['1.6'])
Y17 = np.array(df1['1.7'])
Y18 = np.array(df1['1.8'])
Y19 = np.array(df1['1.9'])

In [19]:
X_features

array([[  1,   1,   0, ...,   0,   0,   0],
       [  1,   0,   1, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       ...,
       [718,   0,   0, ...,   0,   1,   0],
       [718,   0,   0, ...,   0,   1,   0],
       [718,   0,   0, ...,   0,   0,   1]], dtype=int64)

In [20]:
#Importing Linear Regression 
from sklearn.linear_model import LinearRegression
Lin1= LinearRegression()
Lin1.fit(X_features,Y1)

LinearRegression()

In [21]:
Y_pred_1 = Lin1.predict(X_test)
Y_pred_1

array([0.5607357 , 0.49578652, 0.41691396, ..., 0.24966945, 0.24966945,
       0.23333001])

In [22]:
# So we are predicting all the column from 0.1 to 1.9 into same algo
# This is for Y2 means 0.2
Lin1.fit(X_features,Y2)
Y_pred_2 = Lin1.predict(X_test)
Y_pred_2
# just like this we prdicting the all values

array([0.4914274 , 0.43678997, 0.37075603, ..., 0.22658672, 0.22658672,
       0.21204398])

In [23]:
Main_df = pd.DataFrame()
Main_df['0.1'] = Y_pred_1
Main_df['0.2'] = Y_pred_2
print(Main_df)

           0.1       0.2
0     0.560736  0.491427
1     0.495787  0.436790
2     0.416914  0.370756
3     0.384595  0.344224
4     0.362968  0.326661
...        ...       ...
1135  0.282493  0.257043
1136  0.263567  0.239320
1137  0.249669  0.226587
1138  0.249669  0.226587
1139  0.233330  0.212044

[1140 rows x 2 columns]


In [24]:
# For Y3
Lin1.fit(X_features,Y3)
Y_pred_3 = Lin1.predict(X_test)
Main_df['0.3'] = Y_pred_3
# For Y4
Lin1.fit(X_features,Y4)
Y_pred_4 = Lin1.predict(X_test)
Main_df['0.4'] = Y_pred_4
# For Y5
Lin1.fit(X_features,Y5)
Y_pred_5 = Lin1.predict(X_test)
Main_df['0.5'] = Y_pred_5
# For Y6
Lin1.fit(X_features,Y6)
Y_pred_6 = Lin1.predict(X_test)
Main_df['0.6'] = Y_pred_6
# For Y7
Lin1.fit(X_features,Y7)
Y_pred_7 = Lin1.predict(X_test)
Main_df['0.7'] = Y_pred_7
# For Y8
Lin1.fit(X_features,Y8)
Y_pred_8 = Lin1.predict(X_test)
Main_df['0.8'] = Y_pred_8
# For Y9
Lin1.fit(X_features,Y9)
Y_pred_9 = Lin1.predict(X_test)
Main_df['0.9'] = Y_pred_9
# For Y10
Lin1.fit(X_features,Y10)
Y_pred_10 = Lin1.predict(X_test)
Main_df['1'] = Y_pred_10
# For Y11
Lin1.fit(X_features,Y11)
Y_pred_11 = Lin1.predict(X_test)
Main_df['1.1'] = Y_pred_11
# For Y12
Lin1.fit(X_features,Y12)
Y_pred_12 = Lin1.predict(X_test)
Main_df['1.2'] = Y_pred_12
# For Y13
Lin1.fit(X_features,Y13)
Y_pred_13 = Lin1.predict(X_test)
Main_df['1.3'] = Y_pred_13
# For Y14
Lin1.fit(X_features,Y14)
Y_pred_14 = Lin1.predict(X_test)
Main_df['1.4'] = Y_pred_14
# For Y15
Lin1.fit(X_features,Y15)
Y_pred_15 = Lin1.predict(X_test)
Main_df['1.5'] = Y_pred_15
# For Y16
Lin1.fit(X_features,Y16)
Y_pred_16 = Lin1.predict(X_test)
Main_df['1.6'] = Y_pred_16
# For Y17
Lin1.fit(X_features,Y17)
Y_pred_17 = Lin1.predict(X_test)
Main_df['1.7'] = Y_pred_17
# For 18
Lin1.fit(X_features,Y18)
Y_pred_18 = Lin1.predict(X_test)
Main_df['1.8'] = Y_pred_18
# For 19
Lin1.fit(X_features,Y19)
Y_pred_19 = Lin1.predict(X_test)
Main_df['1.9'] = Y_pred_19

In [25]:
Main_df

0.1       0.2       0.3       0.4       0.5       0.6       0.7  \
0     0.560736  0.491427  0.431730  0.379037  0.331680  0.288575  0.249137   
1     0.495787  0.436790  0.386163  0.341682  0.301949  0.266100  0.233738   
2     0.416914  0.370756  0.331548  0.297502  0.267531  0.240999  0.217644   
3     0.384595  0.344224  0.310172  0.280836  0.255244  0.232821  0.213299   
4     0.362968  0.326661  0.296229  0.270180  0.247609  0.227968  0.210961   
...        ...       ...       ...       ...       ...       ...       ...   
1135  0.282493  0.257043  0.235946  0.218113  0.202854  0.189635  0.178082   
1136  0.263567  0.239320  0.219269  0.202221  0.187467  0.174682  0.163547   
1137  0.249669  0.226587  0.207651  0.191640  0.177824  0.165743  0.155185   
1138  0.249669  0.226587  0.207651  0.191640  0.177824  0.165743  0.155185   
1139  0.233330  0.212044  0.194796  0.180383  0.168079  0.157427  0.148122   

           0.8       0.9         1       1.1       1.2       1.3       1.4  \
0     0.213479  0.183357  0.164608  0.164139  0.176052  0.192141  0.209040   
1     0.205089  0.181587  0.166713  0.163762  0.170060  0.180683  0.192812   
2     0.197616  0.181624  0.170930  0.166486  0.167375  0.171641  0.177712   
3     0.196690  0.183331  0.173837  0.168711  0.167462  0.168966  0.172197   
4     0.196504  0.184728  0.175957  0.170512  0.168063  0.167866  0.169218   
...        ...       ...       ...       ...       ...       ...       ...   
1135  0.167921  0.158999  0.151358  0.145246  0.140561  0.137034  0.134459   
1136  0.153809  0.145334  0.138180  0.132601  0.128491  0.125559  0.123582   
1137  0.146025  0.138138  0.131575  0.126576  0.123014  0.120579  0.119033   
1138  0.146025  0.138138  0.131575  0.126576  0.123014  0.120579  0.119033   
1139  0.140055  0.133214  0.127619  0.123473  0.120617  0.118725  0.117563   

           1.5       1.6       1.7       1.8       1.9  
0     0.225592  0.241405  0.256372  0.270498  0.283831  
1     0.205204  0.217332  0.228986  0.240094  0.250650  
2     0.184626  0.191845  0.199078  0.206173  0.213058  
3     0.176421  0.181168  0.186151  0.191199  0.196212  
4     0.171567  0.174526  0.177841  0.181345  0.184932  
...        ...       ...       ...       ...       ...  
1135  0.132665  0.131498  0.130830  0.130557  0.130595  
1136  0.122362  0.121731  0.121551  0.121714  0.122135  
1137  0.118172  0.117830  0.117874  0.118203  0.118744  
1138  0.118172  0.117830  0.117874  0.118203  0.118744  
1139  0.116943  0.116722  0.116791  0.117072  0.117511  

[1140 rows x 19 columns]

In [26]:
# Importing the Template File for Giving Template
temp = pd.read_csv('prediction_template.csv')
temp.head()

Date Tenor  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...   1  1.1  \
0  10/15/2019    2M  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ... NaN  NaN   
1  10/15/2019    3M  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ... NaN  NaN   
2  10/15/2019    6M  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ... NaN  NaN   
3  10/15/2019    9M  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ... NaN  NaN   
4  10/15/2019    1Y  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ... NaN  NaN   

   1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 21 columns]

In [27]:
# Putting the Date and Tenor into Final Main_df
Main_df.insert(0,'Date',temp['Date'])
Main_df.insert(1,'Tenor',temp['Tenor'])
Main_df.head()

Date Tenor       0.1       0.2       0.3       0.4       0.5  \
0  10/15/2019    2M  0.560736  0.491427  0.431730  0.379037  0.331680   
1  10/15/2019    3M  0.495787  0.436790  0.386163  0.341682  0.301949   
2  10/15/2019    6M  0.416914  0.370756  0.331548  0.297502  0.267531   
3  10/15/2019    9M  0.384595  0.344224  0.310172  0.280836  0.255244   
4  10/15/2019    1Y  0.362968  0.326661  0.296229  0.270180  0.247609   

        0.6       0.7       0.8  ...         1       1.1       1.2       1.3  \
0  0.288575  0.249137  0.213479  ...  0.164608  0.164139  0.176052  0.192141   
1  0.266100  0.233738  0.205089  ...  0.166713  0.163762  0.170060  0.180683   
2  0.240999  0.217644  0.197616  ...  0.170930  0.166486  0.167375  0.171641   
3  0.232821  0.213299  0.196690  ...  0.173837  0.168711  0.167462  0.168966   
4  0.227968  0.210961  0.196504  ...  0.175957  0.170512  0.168063  0.167866   

        1.4       1.5       1.6       1.7       1.8       1.9  
0  0.209040  0.225592  0.241405  0.256372  0.270498  0.283831  
1  0.192812  0.205204  0.217332  0.228986  0.240094  0.250650  
2  0.177712  0.184626  0.191845  0.199078  0.206173  0.213058  
3  0.172197  0.176421  0.181168  0.186151  0.191199  0.196212  
4  0.169218  0.171567  0.174526  0.177841  0.181345  0.184932  

[5 rows x 21 columns]

In [28]:
# saving the file into system
#Main_df.to_csv(r'F:\Hackathon\Wells Fargo Quantitative AI Hackathon(Trading)\final_prediction.csv')
print("Done")

Done


In [29]:
# Ploting the 3d Graph for pradiction file
from mpl_toolkits import mplot3d
from matplotlib.tri import Triangulation
import plotly.graph_objects as go
import plotly.express as px

In [30]:
df = pd.read_csv("final_prediction.csv")

In [32]:
fig = go.Figure(data=[go.Surface(z=df.values)])
fig.update_layout(title='Implied Volatility Surface Dynamics', autosize =False, width=500 , height= 500, margin =dict(l= 65, b=65 ,r=50 , t=90,))
xaxis = go.layout.XAxis(title= go.layout.xaxis.Title(text='Tenor in days'))
yaxis = dict(title ='Implied Volatility')
zaxis = dict(title ='Moneyness')
fig.show()